import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";
import type { ComponentProps } from "react";

import { cn } from "@/lib/utils";

/**
 * Buttons.
 *
 * The capsule shape is the site's own and is kept, through
 * `--radius-control`. What went is the finish: a top-down gradient wash, an
 * inner highlight and a coloured glow that bloomed under the button on hover —
 * three effects stacked to imitate a lit plastic key. A solid brand fill that
 * deepens on hover says the same thing in one move, and lets the label carry
 * the invitation, which on a church page is what the reader is actually
 * responding to.
 */
const buttonVariants = cva(
  // No `whitespace-nowrap`: Tamil CTAs ("எங்களுடன் ஆராதியுங்கள்") are long enough
  // that pinning them to one line pushes the label past the button, which the
  // mobile menu then clips. Sizes below use `min-h` so a wrapped label grows the
  // button instead of spilling out of it.
  "inline-flex items-center justify-center gap-2.5 rounded-[var(--radius-control)] text-center font-medium transition-[background-color,border-color,color,transform] duration-300 ease-[var(--ease-out-expo)] active:scale-[0.98] disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0",
  {
    variants: {
      variant: {
        primary:
          "bg-[var(--primary)] text-[var(--primary-foreground)] hover:bg-brand-800",
        secondary:
          "border border-sand-300 bg-transparent text-[var(--foreground)] hover:border-sand-400 hover:bg-sand-100",
        accent: "bg-accent-700 text-white hover:bg-accent-800",
        ghost: "text-[var(--foreground)] hover:bg-sand-100",
        link: "text-[var(--primary)] underline-offset-4 hover:underline",
        /* For placement over dark imagery, e.g. the cinematic hero. */
        onDark:
          "border border-white/40 bg-transparent text-white hover:border-white hover:bg-white/10",
      },
      size: {
        sm: "min-h-9 px-4 py-1.5 text-[0.8125rem]",
        md: "min-h-11 px-6 py-2 text-sm",
        lg: "min-h-13 px-8 py-2.5 text-[0.9375rem]",
        icon: "size-10 shrink-0",
      },
    },
    defaultVariants: {
      variant: "primary",
      size: "md",
    },
  },
);

export interface ButtonProps
  extends ComponentProps<"button">,
    VariantProps<typeof buttonVariants> {
  /** Render as the child element (e.g. a `Link`) instead of a `<button>`. */
  asChild?: boolean;
}

export function Button({
  className,
  variant,
  size,
  asChild = false,
  ...props
}: ButtonProps) {
  const Comp = asChild ? Slot : "button";

  return (
    <Comp
      /*
       * A stable hook for season styling. The variant classes are generated by
       * `cva` and change whenever the design does, so a stylesheet that wanted
       * to reach every button would have to guess at them; this attribute is
       * the contract. Carries no styling of its own.
       */
      data-button=""
      className={cn(buttonVariants({ variant, size }), className)}
      {...props}
    />
  );
}

export { buttonVariants };
